### ISSUE TITLE
restart meteor results in all messages being processed again

### ISSUE THREAD

**Issue by portorenovato** [foxdog-studios/pyddp#4]
hello i have a python script to connect to my meteor.

if i stop meteor and start it again all messages already sent from python are sent again 

is this normal ?

**Comment by dj-foxxy** [comment]
Nope, that's not normal. Sound like a bug where the outbox is not getting
cleaned. I'll have a look on Wednesday. Thanks.

**Comment by ramstein74** [comment]
Hello, any news about this issue?
thank you

**Comment by dj-foxxy** [comment]
Hi sorry, I'd like to say I've not had the time to look at this, but that would be a lie. The problem is we've moved away from using Python with Meteor and instead write native Node Add-ons. So, this library is being neglected. But, I'll look right now.

**Comment by dj-foxxy** [comment]
Uploaded new version to PyPI: https://pypi.python.org/pypi/pyddp/
